In [17]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

/data/ShenShuo/miniconda3/envs/pets2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/data/ShenShuo/miniconda3/envs/pets2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/data/ShenShuo/miniconda3/envs/pets2/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/data/ShenShuo/miniconda3/envs/pets2/lib

# shuffle rows

In [10]:
def shuffle_rows(arr):
    idxs = np.argsort(np.random.uniform(size=arr.shape), axis=-1)
    return arr[np.arange(arr.shape[0])[:, None], idxs]

a = np.random.uniform(size=(3,3))
print(a, "\n")
a = shuffle_rows(a)
print(a)

[[0.29099962 0.85232345 0.06168549]
 [0.83157792 0.75334306 0.04860298]
 [0.52683872 0.35206898 0.68470035]] 

[[0.06168549 0.85232345 0.29099962]
 [0.83157792 0.75334306 0.04860298]
 [0.35206898 0.52683872 0.68470035]]


In [11]:
np.random.randint()
np.random.permutation()

<function RandomState.randint>

# MPC ._compile_cost

In [13]:
# action seq
a = np.arange(12).reshape(2,2,3)
b = a[:, :, None]
c = np.tile(b, [1, 1, 5, 1])
print(a.shape, b.shape, c.shape)

(2, 2, 3) (2, 2, 1, 3) (2, 2, 5, 3)


In [16]:
# obs seq
a = np.arange(6).reshape(2,3)[None]
b = np.tile(a, [2, 1])
print(a.shape, b.shape)
print(a, "\n")
print(b, "\n")

(1, 2, 3) (1, 4, 3)
[[[0 1 2]
  [3 4 5]]] 

[[[0 1 2]
  [3 4 5]
  [0 1 2]
  [3 4 5]]] 



In [55]:
random_array = tf.random_uniform([8, 5])
sort_idxs = tf.nn.top_k(
    random_array,
    k=5
).indices


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    random_array, idx = sess.run([random_array, sort_idxs])
print(random_array, "\n",idx,  "\n", idx.shape)

[[0.98492837 0.15708661 0.30006194 0.57380354 0.5511217 ]
 [0.2919929  0.4022026  0.1956563  0.8473238  0.49093473]
 [0.87433267 0.7644963  0.6649406  0.49275243 0.86384547]
 [0.5642768  0.6708387  0.93194366 0.21606135 0.71665406]
 [0.1282978  0.01437759 0.50262654 0.32990038 0.5678843 ]
 [0.37182093 0.62550235 0.11662447 0.34997082 0.18829215]
 [0.57517385 0.47611594 0.70101523 0.22044003 0.3974806 ]
 [0.16406643 0.15351188 0.40816474 0.08074033 0.11120546]] 
 [[0 3 4 2 1]
 [3 4 1 0 2]
 [0 4 1 2 3]
 [2 4 1 0 3]
 [4 2 3 0 1]
 [1 0 3 4 2]
 [2 0 1 4 3]
 [2 0 1 4 3]] 
 (8, 5)


In [56]:
tmp = tf.tile(tf.range(8)[:, None], [1, 5])[:, :, None]
with tf.Session() as sess:
    result = sess.run(tmp)
print(result.shape)

idxs = np.concatenate([result,idx[:,:,None]],axis=-1)
print(idxs.shape)

(8, 5, 1)
(8, 5, 2)


In [7]:
def make_bool(arg):
    if arg == "False" or arg == "false" or not bool(arg):
        return False
    else:
        return True
print(make_bool('False'))

False
